name: build

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master

jobs:
  jacoco-ut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"
      - name: Build with Maven
        run: mvn clean jacoco:prepare-agent test -Punit-test,coverage
      - uses: actions/upload-artifact@v7
        with:
          name: jacoco
          path: target/jacoco.exec
  jacoco-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"
      - name: Build with Maven
        run: mvn clean  jacoco:prepare-agent-integration integration-test -Parq-glassfish-managed,coverage
      - uses: actions/upload-artifact@v7
        with:
          name: jacoco-it
          path: target/jacoco-it.exec
  jacoco-report:
    runs-on: ubuntu-latest
    needs:
      - jacoco-ut
      - jacoco-it
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"
      - uses: actions/download-artifact@v8
        with:
          path: target/
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R target/
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar -Pcoverage \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=$SONAR_TOKEN \
          -Dsonar.organization=hantsy \
          -Dsonar.projectKey=hantsy_jakartaee12-starter-boilerplate \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/*/jacoco.xml \
          -Dsonar.coverage.exclusions=**/dto/*,**/*Configuration.*,**/SampleDataGenerator.*

